<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>ee334d74-fe7c-4c90-98e7-55ba7e59d5c4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Labosi-ASP.NET.Tests\**\*.cs" />
    <Compile Remove="Labosi-ASP.NET.E2ETests\**\*.cs" />
    <Content Remove="Labosi-ASP.NET.Tests\**\*" />
    <Content Remove="Labosi-ASP.NET.E2ETests\**\*" />
    <EmbeddedResource Remove="Labosi-ASP.NET.Tests\**\*" />
    <EmbeddedResource Remove="Labosi-ASP.NET.E2ETests\**\*" />
    <None Remove="Labosi-ASP.NET.Tests\**\*" />
    <None Remove="Labosi-ASP.NET.E2ETests\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.27" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.27" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.27" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.27">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.27" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.27">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
