// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NasIndexer.Data;

#nullable disable

namespace LabosiASP.NET.Migrations
{
    [DbContext(typeof(NasIndexerDbContext))]
    [Migration("20260519182421_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("FileItemFileTag", b =>
                {
                    b.Property<int>("FilesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FilesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("FileItemTags", (string)null);
                });

            modelBuilder.Entity("NasIndexer.Model.DirectoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScanJobId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ScanJobId");

                    b.ToTable("DirectoryItems", (string)null);
                });

            modelBuilder.Entity("NasIndexer.Model.FileChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangeType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("FileChangeLogs", (string)null);
                });

            modelBuilder.Entity("NasIndexer.Model.FileItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DirectoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryId");

                    b.ToTable("FileItems", (string)null);
                });

            modelBuilder.Entity("NasIndexer.Model.FileTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FileTags", (string)null);
                });

            modelBuilder.Entity("NasIndexer.Model.NasServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastScan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NasServers", (string)null);
                });

            modelBuilder.Entity("NasIndexer.Model.ScanJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("NasServerId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProcessedFiles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalFiles")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NasServerId");

                    b.ToTable("ScanJobs", (string)null);
                });

            modelBuilder.Entity("NasIndexer.Model.SystemAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SystemAdmins", (string)null);
                });

            modelBuilder.Entity("NasServerSystemAdmin", b =>
                {
                    b.Property<int>("ManagedAdminsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManagedServersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ManagedAdminsId", "ManagedServersId");

                    b.HasIndex("ManagedServersId");

                    b.ToTable("SystemAdminNasServers", (string)null);
                });

            modelBuilder.Entity("FileItemFileTag", b =>
                {
                    b.HasOne("NasIndexer.Model.FileItem", null)
                        .WithMany()
                        .HasForeignKey("FilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NasIndexer.Model.FileTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NasIndexer.Model.DirectoryItem", b =>
                {
                    b.HasOne("NasIndexer.Model.DirectoryItem", "Parent")
                        .WithMany("SubDirectories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NasIndexer.Model.ScanJob", "ScanJob")
                        .WithMany("ScannedDirectories")
                        .HasForeignKey("ScanJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parent");

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("NasIndexer.Model.FileChangeLog", b =>
                {
                    b.HasOne("NasIndexer.Model.FileItem", "File")
                        .WithMany("ChangeLogs")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("NasIndexer.Model.FileItem", b =>
                {
                    b.HasOne("NasIndexer.Model.DirectoryItem", "Directory")
                        .WithMany("Files")
                        .HasForeignKey("DirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Directory");
                });

            modelBuilder.Entity("NasIndexer.Model.ScanJob", b =>
                {
                    b.HasOne("NasIndexer.Model.NasServer", "NasServer")
                        .WithMany("ScanJobs")
                        .HasForeignKey("NasServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NasServer");
                });

            modelBuilder.Entity("NasServerSystemAdmin", b =>
                {
                    b.HasOne("NasIndexer.Model.SystemAdmin", null)
                        .WithMany()
                        .HasForeignKey("ManagedAdminsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NasIndexer.Model.NasServer", null)
                        .WithMany()
                        .HasForeignKey("ManagedServersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NasIndexer.Model.DirectoryItem", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("SubDirectories");
                });

            modelBuilder.Entity("NasIndexer.Model.FileItem", b =>
                {
                    b.Navigation("ChangeLogs");
                });

            modelBuilder.Entity("NasIndexer.Model.NasServer", b =>
                {
                    b.Navigation("ScanJobs");
                });

            modelBuilder.Entity("NasIndexer.Model.ScanJob", b =>
                {
                    b.Navigation("ScannedDirectories");
                });
#pragma warning restore 612, 618
        }
    }
}
